### ISSUE TITLE
Add a free license

### ISSUE THREAD

**Issue by pizzamaker** [Alexxz/Hawkingquotes#1]
Please add a free license, preferably GPLv3+

https://www.gnu.org/licenses/license-list.html

It needs a free license to truly be "open source". Also, it would be nice to have this added to F-Droid: https://f-droid.org

**Comment by Alexxz** [comment]
@pizzamaker If  2-clause BSD license fine for f-droid.org project?

**Comment by pizzamaker** [comment]
Yeah, that license is free :)
